name: "ðŸ› Bug Report"
description: Only if something isn't working as expected ðŸ¤”, otherwise please open a discussion.
title: "[Bug]: "

body:
  - type: markdown
    attributes:
      value: |
        **Thanks for reporting an issue!**

        **Issues are expected to lead to changes in the repository, like code or documentation improvements or bug fixes.**
        If you have handling problems or questions, consider to post in [Discussions](../discussions) instead.

        # Environment

  - type: dropdown
    id: Board
    attributes:
      label: The type of board you are using.
      options:
        - Arduino ATmega328* board (UNO, Nano, etc.)
        - Arduino ATmega2560 board (Mega)
        - Arduino ATmega32U4 board (Leonardo, etc.)
        - Arduino ATmega4809 megaAVR board (NanoEvery)
        - Arduino SAM board (Due)
        - Arduino SAMD board (Zero, MKR*)
        - ATtiny85 board (ATTinyCore by Spence Conde)
        - Digispark board
        - ATtiny3217 board (TinyCore)
        - ESP32 board - first check https://github.com/crankyoldgit/IRremoteESP8266
        - STM32F1 board (BluePill)
        - Teensy board
        - Other - please specify below
    validations:
      required: true

  - type: dropdown
    id: IDE
    attributes:
      label: What IDE are you using?
      options:
        - Arduino IDE
        - Arduino Web Editor
        - Arduino Pro IDE
        - Sloeber IDE
        - PlatformIO IDE
        - Other - please specify below
      multiple: false
    validations:
      required: true

  - type: dropdown
    id: IR_Protocol
    attributes:
      label: What IR protocol are you using?
      options:
        - Unknown
        - BoseWave
        - Denon
        - Dish
        - JVC
        - Lego
        - LG
        - NEC
        - Panasonic
        - RC5, RC6
        - Samsung
        - Sharp
        - Sony
        - Whynter
        - Other - please specify below
      multiple: true
    validations:
      required: true

  - type: input
    id: IR_Pin
    attributes:
      label: Pin(s) used for IR-receive, if not default.
      value: "Arduino pin number: "
    validations:
      required: false

  - type: checkboxes
    id: Checked_examples
    attributes:
      label: Example(s) you have checked while hunting the bug.
      description: Please do not submit a bug report without testing at least one or more examples!
      options:
        - label: SimpleReceiver
        - label: ReceiveDemo
        - label: SendRawDemo
        - label: ReceiverTimingAnalysis
        - label: MinimalReceiver
        - label: ReceiveAndSend
        - label: SimpleSender
        - label: SendDemo
        - label: SendLGAirConditionerDemo
        - label: UnitTest
        - label: Other - please specify below
        - label: I checked, if at least one of the examples was working.
          required: true

  - type: checkboxes
    id: Failed_examples
    attributes:
      label: Example(s) to reproduce the issue.
      description: Select only the examples which shows your error.
      options:
        - label: SimpleReceiver
        - label: ReceiveDemo
        - label: SendRawDemo
        - label: ReceiverTimingAnalysis
        - label: MinimalReceiver
        - label: ReceiveAndSend
        - label: SimpleSender
        - label: SendDemo
        - label: SendLGAirConditionerDemo
        - label: UnitTest
        - label: Other - please specify below

  - type: checkboxes
    id: Version
    attributes:
      label: The library version you are working with.
      description: |
        You may use the latest repo version, which is not (yet) released, but may contain some bugfixes.
        Your current library version number can be found with *Arduino > Tools > Manage Libraries..* (Ctrl+Shift+I)
        and is printed to serial output at the startup of every example.
      options:
        - label: I use the [latest Arduino library version](../releases) and verified this!
        - label: I use the latest repo version ([download link](../archive/master.zip)) and verified this!

  - type: markdown
    attributes:
      value: |
        # Bug descripion

  - type: textarea
    id: bug-steps
    attributes:
      label: What are the steps to reproduce this issue?
      placeholder: |
        1.
        2.
        3.
        4. See error
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: What happens?
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: bug-logs
    attributes:
      label: The serial output which indicates the error happened.
      description: |
        Please copy and paste any relevant serial output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false

  - type: textarea
    id: bug-expectation
    attributes:
      label: What were you expecting to happen?
      description: A clear and concise description of what was supposed to happen.
    validations:
      required: false

  - type: textarea
    id: bug-context
    attributes:
      label: Additional context.
      description: Add any other context you can provide about the problem here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        # Checklist

  - type: checkboxes
    id: Commitments
    attributes:
      label: Final checklist for the bug report.
      options:
        - label: I have **read** the README.md file thoroughly
          required: true
        - label: I have searched existing issues to see if there is anything I have missed.
          required: true
        - label: I have browsed the examples for one, that matches my use case.
          required: true
        - label: The title of the issue is helpful and relevant.
          required: true

