name: "🐛 Bug Report"
description: Only if something isn't working as expected 🤔, otherwise please open a discussion.
title: "[Bug]: "

body:
  - type: markdown
    attributes:
      value: |
        **Thanks for reporting an issue!**

        **Issues are expected to lead to changes in the repository, like code or documentation improvements or bug fixes.**
        If you have handling problems or questions, consider to post in [Discussions](../discussions) instead.

  - type: input
    id: Board_FQBN
    attributes:
      label: Please specify **FQBN** (Fully Qualified Board Name).
        It is the first line in the compiler output in the Arduino IDE 2.x.
        E.g. "esp32:esp32:featheresp32:FlashFreq=80".
        The FQBN starts with the core name, which is essential for bugfixing.
        For example, at least two prominent cores are available for the Bluepill board, namely STMicroelectronics and STM32duino.
        Without the FQBN we are most likely not able to fix the the issue.
    validations:
      required: true

  - type: input
    id: Exotic_core_URL
    attributes:
      label: The board manager URL used for exotic cores.
      value: "https://"
    validations:
      required: false

  - type: dropdown
    id: IDE
    attributes:
      label: What IDE are you using?
      options:
        - Arduino 2.x IDE
        - PlatformIO IDE
        - Arduino 1.x IDE
        - Arduino Web Editor
        - Sloeber IDE
        - Other - please specify below
      multiple: false
    validations:
      required: true

  - type: dropdown
    id: IR_Protocol
    attributes:
      label: What IR protocol are you using?
      options:
        - Unknown
        - BoseWave
        - Denon
        - Dish
        - FAST
        - JVC
        - Lego
        - LG
        - NEC
        - Panasonic
        - RC5, RC6
        - Samsung
        - Sharp
        - Sony
        - Universal Pulse Distance
        - Whynter
        - Other - please specify below
      multiple: true
    validations:
      required: true

  - type: input
    id: IR_Pin
    attributes:
      label: Pin(s) used for IR-receive, if not default.
      value: "Arduino pin number: default"
    validations:
      required: false

  - type: checkboxes
    id: Checked_examples
    attributes:
      label: Example(s) you have checked while hunting the bug.
      description: Please do not submit a bug report without testing at least one or more examples!
      options:
        - label: SimpleReceiver
        - label: ReceiveDemo
        - label: SendRawDemo
        - label: ReceiverTimingAnalysis
        - label: ReceiveDump
        - label: TinyReceiver
        - label: TinySender
        - label: ReceiveAndSend
        - label: SimpleSender
        - label: SendDemo
        - label: UnitTest
        - label: Other - please specify below
        - label: I checked, whether at least one of the examples was working.
          required: true

  - type: checkboxes
    id: Failed_examples
    attributes:
      label: Example(s) to reproduce the issue.
      description: Select only the examples which shows your error.
      options:
        - label: SimpleReceiver
        - label: ReceiveDemo
        - label: SendRawDemo
        - label: ReceiverTimingAnalysis
        - label: ReceiveDump
        - label: TinyReceiver
        - label: TinySender
        - label: ReceiveAndSend
        - label: SimpleSender
        - label: SendDemo
        - label: UnitTest
        - label: Other - please specify below

  - type: checkboxes
    id: Version
    attributes:
      label: The library version you are working with.
      description: |
        You may use the latest repo version, which is not (yet) released, but may contain some bugfixes.
        Your current library version number can be found with *Arduino > Tools > Manage Libraries..* (Ctrl+Shift+I)
        and is printed to serial output at the startup of every example.
      options:
        - label: I use the [latest Arduino library version](../releases) and verified this!
        - label: I use the latest repo version ([download link](../archive/master.zip)) and verified this!

  - type: markdown
    attributes:
      value: |
        # Bug descripion

  - type: textarea
    id: bug-steps
    attributes:
      label: What are the steps to reproduce this issue?
      placeholder: |
        1.
        2.
        3.
        4.
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: What happens?
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: bug-logs
    attributes:
      label: The output which indicates the error happened.
      description: |
        Please copy and paste any relevant output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false

  - type: textarea
    id: bug-expectation
    attributes:
      label: What were you expecting to happen?
      description: A clear and concise description of what was supposed to happen.
    validations:
      required: false

  - type: textarea
    id: bug-context
    attributes:
      label: Additional context.
      description: Add any other context you can provide about the problem here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        # Checklist

  - type: checkboxes
    id: Commitments
    attributes:
      label: Final checklist for the bug report.
      options:
        - label: I have **read** the README.md file thoroughly
          required: true
        - label: I have browsed the examples for one that matches my use case.
          required: true
        - label: The title of the issue is helpful and relevant.
          required: true

  - type: markdown
    attributes:
      value: |
        ** We will start to close or delete issues that do not follow these guidelines 
        as it doesn't help the contributors who spend time trying to solve issues if the community ignores guidelines!**

