// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:36:17 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Aiwa2".


#include "IRremote.h"
/*
IRP: 
{38k,550}<1,-1|1,-3>(16,-8,D:8,S:5,~D:8,~S:5,F:8,~F:8,1,-42)*[D:0..255,S:0..31,F:0..255]
*/

/*
Protocol documentation:
From 3FG's teaser.
*/

#if SEND_AIWA2

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 550);
            gap(instance, 550);
        }
        break;
        case 1: {
            flash(instance, 550);
            gap(instance, 1650);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Aiwa2.
 * @param D Protocol parameter in the interval [0 .. 255].
 * @param S Protocol parameter in the interval [0 .. 31].
 * @param F Protocol parameter in the interval [0 .. 255].
 */
void IRsend::sendAiwa2(unsigned int D,
        unsigned int S,
        unsigned int F) {
    enableIROut(38000U / 1000U);
    IRsend* instance = this;
    flash(instance, 8800);
    gap(instance, 4400);
    bitField(instance, D, 8U);
    bitField(instance, S, 5U);
    bitField(instance, ~D, 8U);
    bitField(instance, ~S, 5U);
    bitField(instance, F, 8U);
    bitField(instance, ~F, 8U);
    flash(instance, 550);
    gap(instance, 23100);
}

#endif // SEND_AIWA2 
