// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:37:06 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Blaupunkt_relaxed".


#include "IRremote.h"
/*
IRP: 
{30.3k,512}<-1,1|1,-1>(1,-5,1023:10,-44,(1,-5,1:1,F:6,D:3,-236)*,1,-5,1023:10,-44)[F:0..63,D:0..7]
*/

/*
Protocol documentation:

*/

#if SEND_BLAUPUNKT_RELAXED

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            gap(instance, 512);
            flash(instance, 512);
        }
        break;
        case 1: {
            flash(instance, 512);
            gap(instance, 512);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Blaupunkt_relaxed.
 * @param F Protocol parameter in the interval [0 .. 63].
 * @param D Protocol parameter in the interval [0 .. 7].
 */
void IRsend::sendBlaupunkt_relaxed(unsigned int F,
        unsigned int D) {
    enableIROut(30300U / 1000U);
    IRsend* instance = this;
    flash(instance, 512);
    gap(instance, 2560);
    bitField(instance, 1023U, 10U);
    gap(instance, 22528);
}

#endif // SEND_BLAUPUNKT_RELAXED 
