// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:37:14 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Bryston".


#include "IRremote.h"
/*
IRP: 
{38.0k,315}<1,-6|6,-1>(D:10,F:8,-18m)*[D:0..1023,F:0..255]
*/

/*
Protocol documentation:

*/

#if SEND_BRYSTON

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 315);
            gap(instance, 1890);
        }
        break;
        case 1: {
            flash(instance, 1890);
            gap(instance, 315);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Bryston.
 * @param D Protocol parameter in the interval [0 .. 1023].
 * @param F Protocol parameter in the interval [0 .. 255].
 */
void IRsend::sendBryston(unsigned int D,
        unsigned int F) {
    enableIROut(38000U / 1000U);
    IRsend* instance = this;
    bitField(instance, D, 10U);
    bitField(instance, F, 8U);
    gap(instance, 18000);
}

#endif // SEND_BRYSTON 
