// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:37:10 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Bose".


#include "IRremote.h"
/*
IRP: 
{38.0k,500,msb}<1,-1|1,-3>(2,-3,F:8,~F:8,1,-50m)*[F:0..255]
*/

/*
Protocol documentation:

*/

#if SEND_BOSE

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> (width - i - 1)) & 1) {
        case 0: {
            flash(instance, 500);
            gap(instance, 500);
        }
        break;
        case 1: {
            flash(instance, 500);
            gap(instance, 1500);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Bose.
 * @param F Protocol parameter in the interval [0 .. 255].
 */
void IRsend::sendBose(unsigned int F) {
    enableIROut(38000U / 1000U);
    IRsend* instance = this;
    flash(instance, 1000);
    gap(instance, 1500);
    bitField(instance, F, 8U);
    bitField(instance, ~F, 8U);
    flash(instance, 500);
    gap(instance, 50000);
}

#endif // SEND_BOSE 
