// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:37:28 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Canon".


#include "IRremote.h"
/*
IRP: 
{33k,1}<16p,-240p|16p,-175p>(F:1)2[F:0..1]
*/

/*
Protocol documentation:
IR protocol for many Canon cameras. With F=0 it triggers immediately, F=1 it triggers after a delay of approximately two seconds.
*/

#if SEND_CANON

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 485);
            gap(instance, 7273);
        }
        break;
        case 1: {
            flash(instance, 485);
            gap(instance, 5303);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Canon.
 * @param F Protocol parameter in the interval [0 .. 1].
 */
void IRsend::sendCanon(unsigned int F) {
    enableIROut(33000U / 1000U);
    IRsend* instance = this;
    bitField(instance, F, 1U);
    bitField(instance, F, 1U);
}

#endif // SEND_CANON 
