// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:37:55 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Digivision".


#include "IRremote.h"
/*
IRP: 
{38.0k,182}<3,-3|3,-6>(20,-10,D:8,Dev2:8,Dev3:8,20,-10,F:8,~F:8,3,^108m,(20,-20,3,^108m)*)[D:0..255,Dev2:0..255,Dev3:0..255,F:0..255]
*/

/*
Protocol documentation:
See GuangZhou, which has identical framing but with different bit definitions.
*/

#if SEND_DIGIVISION

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);

static unsigned long durationCounter = 0UL;

static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
    durationCounter += (unsigned long) d;
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
    durationCounter += (unsigned long) d;
}

static inline void extent(IRsend* instance, unsigned long d) {
    instance->space((unsigned int)(d - durationCounter));
    durationCounter = 0UL;
}

static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 546);
            gap(instance, 546);
        }
        break;
        case 1: {
            flash(instance, 546);
            gap(instance, 1092);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Digivision.
 * @param D Protocol parameter in the interval [0 .. 255].
 * @param Dev2 Protocol parameter in the interval [0 .. 255].
 * @param Dev3 Protocol parameter in the interval [0 .. 255].
 * @param F Protocol parameter in the interval [0 .. 255].
 */
void IRsend::sendDigivision(unsigned int D,
        unsigned int Dev2,
        unsigned int Dev3,
        unsigned int F) {
    enableIROut(38000U / 1000U);
    IRsend* instance = this;
    durationCounter = 0UL;
    flash(instance, 3640);
    gap(instance, 1820);
    bitField(instance, D, 8U);
    bitField(instance, Dev2, 8U);
    bitField(instance, Dev3, 8U);
    flash(instance, 3640);
    gap(instance, 1820);
    bitField(instance, F, 8U);
    bitField(instance, ~F, 8U);
    flash(instance, 546);
    extent(instance, 108000UL);
}

#endif // SEND_DIGIVISION 
