// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:38:13 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Dishplayer".


#include "IRremote.h"
/*
IRP: 
{38.4k,535,msb}<1,-5|1,-3>(1,-11,(F:6,S:5,D:2,1,-11)+)[F:0..63,S:0..31,D:0..3]
*/

/*
Protocol documentation:
This is not a robust protocol, so spurious decodes are likely.
*/

#if SEND_DISHPLAYER

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> (width - i - 1)) & 1) {
        case 0: {
            flash(instance, 535);
            gap(instance, 2675);
        }
        break;
        case 1: {
            flash(instance, 535);
            gap(instance, 1605);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Dishplayer.
 * @param F Protocol parameter in the interval [0 .. 63].
 * @param S Protocol parameter in the interval [0 .. 31].
 * @param D Protocol parameter in the interval [0 .. 3].
 */
void IRsend::sendDishplayer(unsigned int F,
        unsigned int S,
        unsigned int D) {
    enableIROut(38400U / 1000U);
    IRsend* instance = this;
    flash(instance, 535);
    gap(instance, 5885);
    bitField(instance, F, 6U);
    bitField(instance, S, 5U);
    bitField(instance, D, 2U);
    flash(instance, 535);
    gap(instance, 5885);
}

#endif // SEND_DISHPLAYER 
