// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:38:17 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Dysan".


#include "IRremote.h"
/*
IRP: 
{780,38k}<1,-1|1,-2>(3,-1,D:7,F:8,1,-104m)*[D:0..127,F:0..255]
*/

/*
Protocol documentation:

*/

#if SEND_DYSAN

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 780);
            gap(instance, 780);
        }
        break;
        case 1: {
            flash(instance, 780);
            gap(instance, 1560);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Dysan.
 * @param D Protocol parameter in the interval [0 .. 127].
 * @param F Protocol parameter in the interval [0 .. 255].
 */
void IRsend::sendDysan(unsigned int D,
        unsigned int F) {
    enableIROut(38000U / 1000U);
    IRsend* instance = this;
    flash(instance, 2340);
    gap(instance, 780);
    bitField(instance, D, 7U);
    bitField(instance, F, 8U);
    flash(instance, 780);
    gap(instance, 104000);
}

#endif // SEND_DYSAN 
