// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:38:09 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Dish_Network".


#include "IRremote.h"
/*
IRP: 
{57.6k,406}<1,-7|1,-4>(1,-15,(F:-6,S:5,D:5,1,-15)+)[F:0..63,S:0..31,D:0..31]
*/

/*
Protocol documentation:
This is not a robust protocol, so spurious decodes are likely. See this thread for a discussion.
*/

#if SEND_DISH_NETWORK

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 406);
            gap(instance, 2842);
        }
        break;
        case 1: {
            flash(instance, 406);
            gap(instance, 1624);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Dish_Network.
 * @param F Protocol parameter in the interval [0 .. 63].
 * @param S Protocol parameter in the interval [0 .. 31].
 * @param D Protocol parameter in the interval [0 .. 31].
 */
void IRsend::sendDish_Network(unsigned int F,
        unsigned int S,
        unsigned int D) {
    enableIROut(57600U / 1000U);
    IRsend* instance = this;
    flash(instance, 406);
    gap(instance, 6090);
    bitField(instance, bitReverse(F, (unsigned int)6U), 6U);
    bitField(instance, S, 5U);
    bitField(instance, D, 5U);
    flash(instance, 406);
    gap(instance, 6090);
}

#endif // SEND_DISH_NETWORK 
