// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:38:26 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Emerson".


#include "IRremote.h"
/*
IRP: 
{36.7k,872}<1,-1|1,-3>(4,-4,D:6,F:6,~D:6,~F:6,1,-39)*[D:0..63,F:0..63]
*/

/*
Protocol documentation:

*/

#if SEND_EMERSON

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 872);
            gap(instance, 872);
        }
        break;
        case 1: {
            flash(instance, 872);
            gap(instance, 2616);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Emerson.
 * @param D Protocol parameter in the interval [0 .. 63].
 * @param F Protocol parameter in the interval [0 .. 63].
 */
void IRsend::sendEmerson(unsigned int D,
        unsigned int F) {
    enableIROut(36700U / 1000U);
    IRsend* instance = this;
    flash(instance, 3488);
    gap(instance, 3488);
    bitField(instance, D, 6U);
    bitField(instance, F, 6U);
    bitField(instance, ~D, 6U);
    bitField(instance, ~F, 6U);
    flash(instance, 872);
    gap(instance, 34008);
}

#endif // SEND_EMERSON 
