// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:38:44 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code F12-1".


#include "IRremote.h"
/*
IRP: 
{37.9k,422}<1,-3|3,-1>(D:3,H:1,F:8,-34,D:3,H:1,F:8,-88,D:3,H:1,F:8,-34,D:3,H:1,F:8)*{H=1}[D:0..7,F:0..0xFF]
*/

/*
Protocol documentation:
Taken from DecodeIR, case H=1.
*/

#if SEND_F121

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 422);
            gap(instance, 1266);
        }
        break;
        case 1: {
            flash(instance, 1266);
            gap(instance, 422);
        }
        break;
        }
    }
}
// Local functions; corresponds to Definitions in the IRP.
static inline unsigned int H(unsigned int D,
        unsigned int F) {
    return 1U;
}

/**
 * Function for sending one signal from the protcol F121.
 * @param D Protocol parameter in the interval [0 .. 7].
 * @param F Protocol parameter in the interval [0 .. 255].
 */
void IRsend::sendF121(unsigned int D,
        unsigned int F) {
    enableIROut(37900U / 1000U);
    IRsend* instance = this;
    bitField(instance, D, 3U);
    bitField(instance, H(D, F), 1U);
    bitField(instance, F, 8U);
    gap(instance, 14348);
    bitField(instance, D, 3U);
    bitField(instance, H(D, F), 1U);
    bitField(instance, F, 8U);
    gap(instance, 37136);
    bitField(instance, D, 3U);
    bitField(instance, H(D, F), 1U);
    bitField(instance, F, 8U);
    gap(instance, 14348);
    bitField(instance, D, 3U);
    bitField(instance, H(D, F), 1U);
    bitField(instance, F, 8U);
}

#endif // SEND_F121 
