// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:38:49 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code F32".


#include "IRremote.h"
/*
IRP: 
{37.9k,422,msb}<1,-3|3,-1>(D:8,S:8,F:8,E:8,-100m)*[D:0..255,S:0..255,F:0..255,E:0..255]
*/

/*
Protocol documentation:
The meaning of the 32 bits of data is unknown, and the assignment to D, S, F, and E is arbitrary.
*/

#if SEND_F32

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> (width - i - 1)) & 1) {
        case 0: {
            flash(instance, 422);
            gap(instance, 1266);
        }
        break;
        case 1: {
            flash(instance, 1266);
            gap(instance, 422);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol F32.
 * @param D Protocol parameter in the interval [0 .. 255].
 * @param S Protocol parameter in the interval [0 .. 255].
 * @param F Protocol parameter in the interval [0 .. 255].
 * @param E Protocol parameter in the interval [0 .. 255].
 */
void IRsend::sendF32(unsigned int D,
        unsigned int S,
        unsigned int F,
        unsigned int E) {
    enableIROut(37900U / 1000U);
    IRsend* instance = this;
    bitField(instance, D, 8U);
    bitField(instance, S, 8U);
    bitField(instance, F, 8U);
    bitField(instance, E, 8U);
    gap(instance, 100000);
}

#endif // SEND_F32 
