// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:39:21 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code G.I.Cable".


#include "IRremote.h"
/*
IRP: 
{38.7k,490}<1,-4.5|1,-9>(18,-9,F:8,D:4,C:4,1,-84,(18,-4.5,1,-178)*){C=-(D+F:4+F:4:4)}[D:0..15,F:0..255]
*/

/*
Protocol documentation:
This protocol signals repeats by the use of dittos.
*/

#if SEND_GICABLE

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 490);
            gap(instance, 2205);
        }
        break;
        case 1: {
            flash(instance, 490);
            gap(instance, 4410);
        }
        break;
        }
    }
}
// Local functions; corresponds to Definitions in the IRP.
static inline unsigned int C(unsigned int D,
        unsigned int F) {
    return -(((D) + (finiteBitField(F, 4U, 0, false, false))) + (finiteBitField(F, 4U, 4U, false, false)));
}

/**
 * Function for sending one signal from the protcol GICable.
 * @param D Protocol parameter in the interval [0 .. 15].
 * @param F Protocol parameter in the interval [0 .. 255].
 */
void IRsend::sendGICable(unsigned int D,
        unsigned int F) {
    enableIROut(38700U / 1000U);
    IRsend* instance = this;
    flash(instance, 8820);
    gap(instance, 4410);
    bitField(instance, F, 8U);
    bitField(instance, D, 4U);
    bitField(instance, C(D, F), 4U);
    flash(instance, 490);
    gap(instance, 41160);
}

#endif // SEND_GICABLE 
