// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:39:49 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code GXB".


#include "IRremote.h"
/*
IRP: 
{38.3k,520,msb}<1,-3|3,-1>(1,-1,D:4,F:8,P:1,1,^100m)*{P=1-#F%2}[D:0..15,F:0..255]
*/

/*
Protocol documentation:
Decoder for a nonstandard Xbox remote.
*/

#if SEND_GXB

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);

static unsigned long durationCounter = 0UL;

static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
    durationCounter += (unsigned long) d;
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
    durationCounter += (unsigned long) d;
}

static inline void extent(IRsend* instance, unsigned long d) {
    instance->space((unsigned int)(d - durationCounter));
    durationCounter = 0UL;
}

static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> (width - i - 1)) & 1) {
        case 0: {
            flash(instance, 520);
            gap(instance, 1560);
        }
        break;
        case 1: {
            flash(instance, 1560);
            gap(instance, 520);
        }
        break;
        }
    }
}
// Local functions; corresponds to Definitions in the IRP.
static inline unsigned int P(unsigned int D,
        unsigned int F) {
    return (1U) - ((bitCount(F))%(2U));
}

/**
 * Function for sending one signal from the protcol GXB.
 * @param D Protocol parameter in the interval [0 .. 15].
 * @param F Protocol parameter in the interval [0 .. 255].
 */
void IRsend::sendGXB(unsigned int D,
        unsigned int F) {
    enableIROut(38300U / 1000U);
    IRsend* instance = this;
    durationCounter = 0UL;
    flash(instance, 520);
    gap(instance, 520);
    bitField(instance, D, 4U);
    bitField(instance, F, 8U);
    bitField(instance, P(D, F), 1U);
    flash(instance, 520);
    extent(instance, 100000UL);
}

#endif // SEND_GXB 
