// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:39:44 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code GwtS".


#include "IRremote.h"
/*
IRP: 
{38.005k,417,lsb}<1|-1>(0:1,D:8,1:2,F:8,1:2,CRC:8,1:1)[D:0..255=144,F:0..255,CRC:0..255]
*/

/*
Protocol documentation:
Protocol for Disney's Glow with the Show Hat/Ears, see this. Unfortunately, the IRP engine cannot compute the CRC, but the user has to enter it manually. The known commands are, together with their F and CRC values, as follows: off 0x60 166 blue 0x61 248 green 0x62 26 cyan 0x63 68 red 0x64 199 magenta 0x65 153 yellow 0x66 123 white 0x67 37 off_r 0x68 100 blue_r 0x69 58 green_r 0x6A 216 cyan_r 0x6B 134 red_r 0x6C 5 magenta_r 0x6D 91 yellow_r 0x6E 185 white_r 0x6F 231
*/

#if SEND_GWTS

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 417);
        }
        break;
        case 1: {
            gap(instance, 417);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol GwtS.
 * @param D Protocol parameter in the interval [0 .. 255].
 * @param F Protocol parameter in the interval [0 .. 255].
 * @param CRC Protocol parameter in the interval [0 .. 255].
 */
void IRsend::sendGwtS(unsigned int D,
        unsigned int F,
        unsigned int CRC) {
    enableIROut(38005U / 1000U);
    IRsend* instance = this;
    bitField(instance, 0U, 1U);
    bitField(instance, D, 8U);
    bitField(instance, 1U, 2U);
    bitField(instance, F, 8U);
    bitField(instance, 1U, 2U);
    bitField(instance, CRC, 8U);
    bitField(instance, 1U, 1U);
}

#endif // SEND_GWTS 
