// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:39:25 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code GI%20RG".


#include "IRremote.h"
/*
IRP: 
{37.3k,1000,msb}<1,-1|1,-3>(5,-3,F:6,S:2,D:8,1,-60)*[D:0..255,S:0..3,F:0..63]
*/

/*
Protocol documentation:
This is a moderately robust protocol, but spurious decodes are still possible. Typical usage is the GI/Next Level/Motorola RC2x00 series.
*/

#if SEND_GIRG

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> (width - i - 1)) & 1) {
        case 0: {
            flash(instance, 1000);
            gap(instance, 1000);
        }
        break;
        case 1: {
            flash(instance, 1000);
            gap(instance, 3000);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol GIRG.
 * @param D Protocol parameter in the interval [0 .. 255].
 * @param S Protocol parameter in the interval [0 .. 3].
 * @param F Protocol parameter in the interval [0 .. 63].
 */
void IRsend::sendGIRG(unsigned int D,
        unsigned int S,
        unsigned int F) {
    enableIROut(37300U / 1000U);
    IRsend* instance = this;
    flash(instance, 5000);
    gap(instance, 3000);
    bitField(instance, F, 6U);
    bitField(instance, S, 2U);
    bitField(instance, D, 8U);
    flash(instance, 1000);
    gap(instance, 60000);
}

#endif // SEND_GIRG 
