// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:40:40 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Konka".


#include "IRremote.h"
/*
IRP: 
{38k,500,msb}<1,-3|1,-5>(6,-6,D:8,F:8,1,-8,1,-46)*[D:0..255,F:0..255]
*/

/*
Protocol documentation:

*/

#if SEND_KONKA

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> (width - i - 1)) & 1) {
        case 0: {
            flash(instance, 500);
            gap(instance, 1500);
        }
        break;
        case 1: {
            flash(instance, 500);
            gap(instance, 2500);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Konka.
 * @param D Protocol parameter in the interval [0 .. 255].
 * @param F Protocol parameter in the interval [0 .. 255].
 */
void IRsend::sendKonka(unsigned int D,
        unsigned int F) {
    enableIROut(38000U / 1000U);
    IRsend* instance = this;
    flash(instance, 3000);
    gap(instance, 3000);
    bitField(instance, D, 8U);
    bitField(instance, F, 8U);
    flash(instance, 500);
    gap(instance, 4000);
    flash(instance, 500);
    gap(instance, 23000);
}

#endif // SEND_KONKA 
