// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:40:45 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Logitech".


#include "IRremote.h"
/*
IRP: 
{38k,127}<3,-4|3,-8>(31,-36,D:4,~D:4,F:8,~F:8,3,-50m)*[D:0..15,F:0..255]
*/

/*
Protocol documentation:
Logitech is used with their PS3 adapter. The IR signal is similar to Kathrein. If a Logitech signal is decoded as Kathrein, the device number and OBC are still correct.
*/

#if SEND_LOGITECH

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 381);
            gap(instance, 508);
        }
        break;
        case 1: {
            flash(instance, 381);
            gap(instance, 1016);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Logitech.
 * @param D Protocol parameter in the interval [0 .. 15].
 * @param F Protocol parameter in the interval [0 .. 255].
 */
void IRsend::sendLogitech(unsigned int D,
        unsigned int F) {
    enableIROut(38000U / 1000U);
    IRsend* instance = this;
    flash(instance, 3937);
    gap(instance, 4572);
    bitField(instance, D, 4U);
    bitField(instance, ~D, 4U);
    bitField(instance, F, 8U);
    bitField(instance, ~F, 8U);
    flash(instance, 381);
    gap(instance, 50000);
}

#endif // SEND_LOGITECH 
