// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:41:16 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Mitsubishi-K".


#include "IRremote.h"
/*
IRP: 
{37k,432}<1,-1|1,-3>(8,-4,35:8,203:8,X:4,D:8,S:8,F:8,T:4,1,-100)*{X=6,T=-S:4:0-S:4:4-F:4:0-F:4:4+15}[D:0..255,F:0..255,S:0..255]
*/

/*
Protocol documentation:
Mitsubishi-K is the member of the Kaseikyo family with OEM_code1=35 and OEM_code2=203.
*/

#if SEND_MITSUBISHIK

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 432);
            gap(instance, 432);
        }
        break;
        case 1: {
            flash(instance, 432);
            gap(instance, 1296);
        }
        break;
        }
    }
}
// Local functions; corresponds to Definitions in the IRP.
static inline unsigned int X(unsigned int D,
        unsigned int F,
        unsigned int S) {
    return 6U;
}

static inline unsigned int T(unsigned int D,
        unsigned int F,
        unsigned int S) {
    return ((((-(finiteBitField(S, 4U, 0, false, false))) - (finiteBitField(S, 4U, 4U, false, false))) - (finiteBitField(F, 4U, 0, false, false))) - (finiteBitField(F, 4U, 4U, false, false))) + (15U);
}

/**
 * Function for sending one signal from the protcol MitsubishiK.
 * @param D Protocol parameter in the interval [0 .. 255].
 * @param F Protocol parameter in the interval [0 .. 255].
 * @param S Protocol parameter in the interval [0 .. 255].
 */
void IRsend::sendMitsubishiK(unsigned int D,
        unsigned int F,
        unsigned int S) {
    enableIROut(37000U / 1000U);
    IRsend* instance = this;
    flash(instance, 3456);
    gap(instance, 1728);
    bitField(instance, 35U, 8U);
    bitField(instance, 203U, 8U);
    bitField(instance, X(D, F, S), 4U);
    bitField(instance, D, 8U);
    bitField(instance, S, 8U);
    bitField(instance, F, 8U);
    bitField(instance, T(D, F, S), 4U);
    flash(instance, 432);
    gap(instance, 43200);
}

#endif // SEND_MITSUBISHIK 
