// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:41:07 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Metz19".


#include "IRremote.h"
/*
IRP: 
{37.9k,106,msb}<4,-9|4,-16>((8,-22,T:1,D:3,~D:3,F:6,~F:6,4,-125m)*,T=1-T)[D:0..7,F:0..63,T@:0..1=0]
*/

/*
Protocol documentation:
The toggle bit T is inverted each time a new button press occurs.
*/

#if SEND_METZ19

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> (width - i - 1)) & 1) {
        case 0: {
            flash(instance, 424);
            gap(instance, 954);
        }
        break;
        case 1: {
            flash(instance, 424);
            gap(instance, 1696);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Metz19.
 * @param D Protocol parameter in the interval [0 .. 7].
 * @param F Protocol parameter in the interval [0 .. 63].
 * @param T Protocol parameter in the interval [0 .. 1].
 */
void IRsend::sendMetz19(unsigned int D,
        unsigned int F,
        unsigned int T) {
    enableIROut(37900U / 1000U);
    IRsend* instance = this;
    flash(instance, 848);
    gap(instance, 2332);
    bitField(instance, T, 1U);
    bitField(instance, D, 3U);
    bitField(instance, ~D, 3U);
    bitField(instance, F, 6U);
    bitField(instance, ~F, 6U);
    flash(instance, 424);
    gap(instance, 125000);
}

#endif // SEND_METZ19 
