// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:43:10 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code pid-0004".


#include "IRremote.h"
/*
IRP: 
{0k,msb}<12,-130|12,-372>(F:6,12,-27m)*[F:0..63]
*/

/*
Protocol documentation:

*/

#if SEND_PID0004

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> (width - i - 1)) & 1) {
        case 0: {
            flash(instance, 12);
            gap(instance, 130);
        }
        break;
        case 1: {
            flash(instance, 12);
            gap(instance, 372);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol pid0004.
 * @param F Protocol parameter in the interval [0 .. 63].
 */
void IRsend::sendpid0004(unsigned int F) {
    enableIROut(0U / 1000U);
    IRsend* instance = this;
    bitField(instance, F, 6U);
    flash(instance, 12);
    gap(instance, 27000);
}

#endif // SEND_PID0004 
