// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:42:52 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Panasonic_Old".


#include "IRremote.h"
/*
IRP: 
{57.6k,833}<1,-1|1,-3>(4,-4,D:5,F:6,~D:5,~F:6,1,-44m)*[D:0..31,F:0..63]
*/

/*
Protocol documentation:

*/

#if SEND_PANASONIC_OLD

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 833);
            gap(instance, 833);
        }
        break;
        case 1: {
            flash(instance, 833);
            gap(instance, 2499);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Panasonic_Old.
 * @param D Protocol parameter in the interval [0 .. 31].
 * @param F Protocol parameter in the interval [0 .. 63].
 */
void IRsend::sendPanasonic_Old(unsigned int D,
        unsigned int F) {
    enableIROut(57600U / 1000U);
    IRsend* instance = this;
    flash(instance, 3332);
    gap(instance, 3332);
    bitField(instance, D, 5U);
    bitField(instance, F, 6U);
    bitField(instance, ~D, 5U);
    bitField(instance, ~F, 6U);
    flash(instance, 833);
    gap(instance, 44000);
}

#endif // SEND_PANASONIC_OLD 
