// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:43:14 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code pid-0083".


#include "IRremote.h"
/*
IRP: 
{42.3k,3000}<1,-3,1,-7|1,-7,1,-3>(F:5,1,-27)*[F:0..31]
*/

/*
Protocol documentation:
This protocol is a very limited design. We have seen it used only in the UEI setup code TV/0159, which is for some TVs brand named Fisher, Sanyo and Sears. It is not likely that any other code set uses this protocol. So if you get a correct decode of pid-0083 you probably have a TV that can be controlled by the TV/0159 setup code.
*/

#if SEND_PID0083

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 3000);
            gap(instance, 9000);
            flash(instance, 3000);
            gap(instance, 21000);
        }
        break;
        case 1: {
            flash(instance, 3000);
            gap(instance, 21000);
            flash(instance, 3000);
            gap(instance, 9000);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol pid0083.
 * @param F Protocol parameter in the interval [0 .. 31].
 */
void IRsend::sendpid0083(unsigned int F) {
    enableIROut(42300U / 1000U);
    IRsend* instance = this;
    bitField(instance, F, 5U);
    flash(instance, 3000);
    gap(instance, 81000);
}

#endif // SEND_PID0083 
