// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:43:01 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code pid-0001".


#include "IRremote.h"
/*
IRP: 
{0k,msb}<24,-9314|24,-13486>(24,-21148,(F:5,1,-28m)+)[F:0..31]
*/

/*
Protocol documentation:

*/

#if SEND_PID0001

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> (width - i - 1)) & 1) {
        case 0: {
            flash(instance, 24);
            gap(instance, 9314);
        }
        break;
        case 1: {
            flash(instance, 24);
            gap(instance, 13486);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol pid0001.
 * @param F Protocol parameter in the interval [0 .. 31].
 */
void IRsend::sendpid0001(unsigned int F) {
    enableIROut(0U / 1000U);
    IRsend* instance = this;
    flash(instance, 24);
    gap(instance, 21148);
    bitField(instance, F, 5U);
    flash(instance, 1);
    gap(instance, 28000);
}

#endif // SEND_PID0001 
