// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:42:56 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code PCTV".


#include "IRremote.h"
/*
IRP: 
{38.4k,832}<-1|1>(2,-8,1,D:8,F:8,2,-100m)[D:0..255,F:0..255]
*/

/*
Protocol documentation:

*/

#if SEND_PCTV

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            gap(instance, 832);
        }
        break;
        case 1: {
            flash(instance, 832);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol PCTV.
 * @param D Protocol parameter in the interval [0 .. 255].
 * @param F Protocol parameter in the interval [0 .. 255].
 */
void IRsend::sendPCTV(unsigned int D,
        unsigned int F) {
    enableIROut(38400U / 1000U);
    IRsend* instance = this;
    flash(instance, 1664);
    gap(instance, 6656);
    flash(instance, 832);
    bitField(instance, D, 8U);
    bitField(instance, F, 8U);
    flash(instance, 1664);
    gap(instance, 100000);
}

#endif // SEND_PCTV 
