// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:43:05 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code pid-0003".


#include "IRremote.h"
/*
IRP: 
{40.2k,389}<2,-2|3,-1>(F:8,~F:8,^102m)*[F:0..255]
*/

/*
Protocol documentation:

*/

#if SEND_PID0003

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);

static unsigned long durationCounter = 0UL;

static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
    durationCounter += (unsigned long) d;
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
    durationCounter += (unsigned long) d;
}

static inline void extent(IRsend* instance, unsigned long d) {
    instance->space((unsigned int)(d - durationCounter));
    durationCounter = 0UL;
}

static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 778);
            gap(instance, 778);
        }
        break;
        case 1: {
            flash(instance, 1167);
            gap(instance, 389);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol pid0003.
 * @param F Protocol parameter in the interval [0 .. 255].
 */
void IRsend::sendpid0003(unsigned int F) {
    enableIROut(40200U / 1000U);
    IRsend* instance = this;
    durationCounter = 0UL;
    bitField(instance, F, 8U);
    bitField(instance, ~F, 8U);
    extent(instance, 102000UL);
}

#endif // SEND_PID0003 
