// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:44:31 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Revox".


#include "IRremote.h"
/*
IRP: 
{0k,15u}<1,-9|1,-19>(1,-29,0:1,D:4,F:6,1,-29,1,-100285u)*[D:0..15,F:0..63]
*/

/*
Protocol documentation:
Revox uses no modulation.
*/

#if SEND_REVOX

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 15);
            gap(instance, 135);
        }
        break;
        case 1: {
            flash(instance, 15);
            gap(instance, 285);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Revox.
 * @param D Protocol parameter in the interval [0 .. 15].
 * @param F Protocol parameter in the interval [0 .. 63].
 */
void IRsend::sendRevox(unsigned int D,
        unsigned int F) {
    enableIROut(0U / 1000U);
    IRsend* instance = this;
    flash(instance, 15);
    gap(instance, 435);
    bitField(instance, 0U, 1U);
    bitField(instance, D, 4U);
    bitField(instance, F, 6U);
    flash(instance, 15);
    gap(instance, 435);
    flash(instance, 15);
    gap(instance, 100285);
}

#endif // SEND_REVOX 
