// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:43:50 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code RC5x".


#include "IRremote.h"
/*
IRP: 
{36k,msb,889}<1,-1|-1,1>((1,~S:1:6,T:1,D:5,-4,S:6,F:6,^114m)*,T=1-T)[D:0..31,S:0..127,F:0..63,T@:0..1=0]
*/

/*
Protocol documentation:
In Philips' (the creator of the protocol) terminology, \"D\" is called \"System\", \"S\" is called \"Command\", and is called \"Data\".
*/

#if SEND_RC5X

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);

static unsigned long durationCounter = 0UL;

static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
    durationCounter += (unsigned long) d;
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
    durationCounter += (unsigned long) d;
}

static inline void extent(IRsend* instance, unsigned long d) {
    instance->space((unsigned int)(d - durationCounter));
    durationCounter = 0UL;
}

static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> (width - i - 1)) & 1) {
        case 0: {
            flash(instance, 889);
            gap(instance, 889);
        }
        break;
        case 1: {
            gap(instance, 889);
            flash(instance, 889);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol RC5x.
 * @param D Protocol parameter in the interval [0 .. 31].
 * @param S Protocol parameter in the interval [0 .. 127].
 * @param F Protocol parameter in the interval [0 .. 63].
 * @param T Protocol parameter in the interval [0 .. 1].
 */
void IRsend::sendRC5x(unsigned int D,
        unsigned int S,
        unsigned int F,
        unsigned int T) {
    enableIROut(36000U / 1000U);
    IRsend* instance = this;
    durationCounter = 0UL;
    flash(instance, 889);
    bitField(instance, ~S >> (6U), 1U);
    bitField(instance, T, 1U);
    bitField(instance, D, 5U);
    gap(instance, 3556);
    bitField(instance, S, 6U);
    bitField(instance, F, 6U);
    extent(instance, 114000UL);
}

#endif // SEND_RC5X 
