// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:44:49 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Samsung20".


#include "IRremote.h"
/*
IRP: 
{38.4k,564}<1,-1|1,-3>(8,-8,D:6,S:6,F:8,1,^100m)*[D:0..63,S:0..63,F:0..255]
*/

/*
Protocol documentation:
This is a moderately robust protocol, but spurious decodes are still possible.
*/

#if SEND_SAMSUNG20

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);

static unsigned long durationCounter = 0UL;

static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
    durationCounter += (unsigned long) d;
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
    durationCounter += (unsigned long) d;
}

static inline void extent(IRsend* instance, unsigned long d) {
    instance->space((unsigned int)(d - durationCounter));
    durationCounter = 0UL;
}

static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 564);
            gap(instance, 564);
        }
        break;
        case 1: {
            flash(instance, 564);
            gap(instance, 1692);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Samsung20.
 * @param D Protocol parameter in the interval [0 .. 63].
 * @param S Protocol parameter in the interval [0 .. 63].
 * @param F Protocol parameter in the interval [0 .. 255].
 */
void IRsend::sendSamsung20(unsigned int D,
        unsigned int S,
        unsigned int F) {
    enableIROut(38400U / 1000U);
    IRsend* instance = this;
    durationCounter = 0UL;
    flash(instance, 4512);
    gap(instance, 4512);
    bitField(instance, D, 6U);
    bitField(instance, S, 6U);
    bitField(instance, F, 8U);
    flash(instance, 564);
    extent(instance, 100000UL);
}

#endif // SEND_SAMSUNG20 
