// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:45:21 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code SIM2".


#include "IRremote.h"
/*
IRP: 
{38.8k,400}<3,-3|3,-7>(6,-7,D:8,F:8,3,^115m)[D:0..255=236,F:0..255]
*/

/*
Protocol documentation:
Reference. In that document, there is a contradiction between the verbal description and the Pronto Hex code given. Here we follow the Pronto form, which is also consistent with DecodeIR.
*/

#if SEND_SIM2

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);

static unsigned long durationCounter = 0UL;

static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
    durationCounter += (unsigned long) d;
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
    durationCounter += (unsigned long) d;
}

static inline void extent(IRsend* instance, unsigned long d) {
    instance->space((unsigned int)(d - durationCounter));
    durationCounter = 0UL;
}

static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 1200);
            gap(instance, 1200);
        }
        break;
        case 1: {
            flash(instance, 1200);
            gap(instance, 2800);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol SIM2.
 * @param D Protocol parameter in the interval [0 .. 255].
 * @param F Protocol parameter in the interval [0 .. 255].
 */
void IRsend::sendSIM2(unsigned int D,
        unsigned int F) {
    enableIROut(38800U / 1000U);
    IRsend* instance = this;
    durationCounter = 0UL;
    flash(instance, 2400);
    gap(instance, 2800);
    bitField(instance, D, 8U);
    bitField(instance, F, 8U);
    flash(instance, 1200);
    extent(instance, 115000UL);
}

#endif // SEND_SIM2 
