// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:46:03 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Sunfire".


#include "IRremote.h"
/*
IRP: 
{38k,560,msb}<1,-1|3,-1>(16,-8,D:4,F:8,~D:4,~F:8,-32)*[D:0..15,F:0..255]
*/

/*
Protocol documentation:

*/

#if SEND_SUNFIRE

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> (width - i - 1)) & 1) {
        case 0: {
            flash(instance, 560);
            gap(instance, 560);
        }
        break;
        case 1: {
            flash(instance, 1680);
            gap(instance, 560);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Sunfire.
 * @param D Protocol parameter in the interval [0 .. 15].
 * @param F Protocol parameter in the interval [0 .. 255].
 */
void IRsend::sendSunfire(unsigned int D,
        unsigned int F) {
    enableIROut(38000U / 1000U);
    IRsend* instance = this;
    flash(instance, 8960);
    gap(instance, 4480);
    bitField(instance, D, 4U);
    bitField(instance, F, 8U);
    bitField(instance, ~D, 4U);
    bitField(instance, ~F, 8U);
    gap(instance, 17920);
}

#endif // SEND_SUNFIRE 
