// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:45:49 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Sony8".


#include "IRremote.h"
/*
IRP: 
{40k,600}<1,-1|2,-1>(4,-1,F:8,^45m)[F:0..255]
*/

/*
Protocol documentation:

*/

#if SEND_SONY8

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);

static unsigned long durationCounter = 0UL;

static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
    durationCounter += (unsigned long) d;
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
    durationCounter += (unsigned long) d;
}

static inline void extent(IRsend* instance, unsigned long d) {
    instance->space((unsigned int)(d - durationCounter));
    durationCounter = 0UL;
}

static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 600);
            gap(instance, 600);
        }
        break;
        case 1: {
            flash(instance, 1200);
            gap(instance, 600);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Sony8.
 * @param F Protocol parameter in the interval [0 .. 255].
 */
void IRsend::sendSony8(unsigned int F) {
    enableIROut(40000U / 1000U);
    IRsend* instance = this;
    durationCounter = 0UL;
    flash(instance, 2400);
    gap(instance, 600);
    bitField(instance, F, 8U);
    extent(instance, 45000UL);
}

#endif // SEND_SONY8 
