// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:44:54 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Samsung36".


#include "IRremote.h"
/*
IRP: 
{37.9k,560,33%}<1,-1|1,-3>(4500u,-4500u,D:8,S:8,1,-9,E:4,F:8,~F:8,1,^108m)*[D:0..255,S:0..255,F:0..255,E:0..15]
*/

/*
Protocol documentation:
Reference.
*/

#if SEND_SAMSUNG36

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);

static unsigned long durationCounter = 0UL;

static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
    durationCounter += (unsigned long) d;
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
    durationCounter += (unsigned long) d;
}

static inline void extent(IRsend* instance, unsigned long d) {
    instance->space((unsigned int)(d - durationCounter));
    durationCounter = 0UL;
}

static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 560);
            gap(instance, 560);
        }
        break;
        case 1: {
            flash(instance, 560);
            gap(instance, 1680);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Samsung36.
 * @param D Protocol parameter in the interval [0 .. 255].
 * @param S Protocol parameter in the interval [0 .. 255].
 * @param F Protocol parameter in the interval [0 .. 255].
 * @param E Protocol parameter in the interval [0 .. 15].
 */
void IRsend::sendSamsung36(unsigned int D,
        unsigned int S,
        unsigned int F,
        unsigned int E) {
    enableIROut(37900U / 1000U);
    IRsend* instance = this;
    durationCounter = 0UL;
    flash(instance, 4500);
    gap(instance, 4500);
    bitField(instance, D, 8U);
    bitField(instance, S, 8U);
    flash(instance, 560);
    gap(instance, 5040);
    bitField(instance, E, 4U);
    bitField(instance, F, 8U);
    bitField(instance, ~F, 8U);
    flash(instance, 560);
    extent(instance, 108000UL);
}

#endif // SEND_SAMSUNG36 
