// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:44:45 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Sampo".


#include "IRremote.h"
/*
IRP: 
{38.4k,833}<1,-1|1,-3>(4,-4,D:6,F:6,S:6,~F:6,1,-39)*[D:0..63,S:0..63,F:0..63]
*/

/*
Protocol documentation:
This is a moderately robust protocol, but spurious decodes are still possible.
*/

#if SEND_SAMPO

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 833);
            gap(instance, 833);
        }
        break;
        case 1: {
            flash(instance, 833);
            gap(instance, 2499);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Sampo.
 * @param D Protocol parameter in the interval [0 .. 63].
 * @param S Protocol parameter in the interval [0 .. 63].
 * @param F Protocol parameter in the interval [0 .. 63].
 */
void IRsend::sendSampo(unsigned int D,
        unsigned int S,
        unsigned int F) {
    enableIROut(38400U / 1000U);
    IRsend* instance = this;
    flash(instance, 3332);
    gap(instance, 3332);
    bitField(instance, D, 6U);
    bitField(instance, F, 6U);
    bitField(instance, S, 6U);
    bitField(instance, ~F, 6U);
    flash(instance, 833);
    gap(instance, 32487);
}

#endif // SEND_SAMPO 
