// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:46:30 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Tivo".


#include "IRremote.h"
/*
IRP: 
{38.4k,564}<1,-1|1,-3>(16,-8,D:8,S:8,F:8,U:4,~F:4:4,1,-78,(16,-4,1,-173)*)[D:133..133=133,S:48..48=48,F:0..255,U:0..15]
*/

/*
Protocol documentation:

*/

#if SEND_TIVO

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 564);
            gap(instance, 564);
        }
        break;
        case 1: {
            flash(instance, 564);
            gap(instance, 1692);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Tivo.
 * @param D Protocol parameter in the interval [133 .. 133].
 * @param S Protocol parameter in the interval [48 .. 48].
 * @param F Protocol parameter in the interval [0 .. 255].
 * @param U Protocol parameter in the interval [0 .. 15].
 */
void IRsend::sendTivo(unsigned int D,
        unsigned int S,
        unsigned int F,
        unsigned int U) {
    enableIROut(38400U / 1000U);
    IRsend* instance = this;
    flash(instance, 9024);
    gap(instance, 4512);
    bitField(instance, D, 8U);
    bitField(instance, S, 8U);
    bitField(instance, F, 8U);
    bitField(instance, U, 4U);
    bitField(instance, ~F >> (4U), 4U);
    flash(instance, 564);
    gap(instance, 43992);
}

#endif // SEND_TIVO 
