// This file was generated by IrpTransmogrifier version 0.2.1dev by bengt
// on Mon Oct 23 11:46:44 CEST 2017
// using command line arguments:
// "-c /home/bengt/harctoolbox/IrpTransmogrifier/tools/../src/main/resources/IrpProtocols.xml --url --loglevel info --logformat %5$s%n code -s src/main/st --dir ../Arduino-IRremote-bm/src -t irremote-renderer-cppsymbols -t irremote-renderer-declarations -t irremote-renderer-code Viewstar".


#include "IRremote.h"
/*
IRP: 
{50.5k,337}<1,-8|1,-5>(~F:5,1,-17)*[F:0..31]
*/

/*
Protocol documentation:
This is not a robust protocol, so spurious decodes are likely.
*/

#if SEND_VIEWSTAR

extern unsigned int finiteBitField(unsigned int data,
        unsigned int width,
        unsigned int chop,
        bool complement,
        bool reverse);
extern unsigned int bitCount(unsigned int data);
extern unsigned int bitReverse(unsigned int data, unsigned int width);


static inline void flash(IRsend* instance, unsigned int d) {
    instance->mark(d);
}

static inline void gap(IRsend* instance, unsigned int d) {
    instance->space(d);
}



static void bitField(IRsend* instance, unsigned int data, unsigned int width) {
    for (unsigned int i = 0; i < width; i++) {
        switch(((unsigned int)data >> i) & 1) {
        case 0: {
            flash(instance, 337);
            gap(instance, 2696);
        }
        break;
        case 1: {
            flash(instance, 337);
            gap(instance, 1685);
        }
        break;
        }
    }
}
/**
 * Function for sending one signal from the protcol Viewstar.
 * @param F Protocol parameter in the interval [0 .. 31].
 */
void IRsend::sendViewstar(unsigned int F) {
    enableIROut(50500U / 1000U);
    IRsend* instance = this;
    bitField(instance, ~F, 5U);
    flash(instance, 337);
    gap(instance, 5729);
}

#endif // SEND_VIEWSTAR 
